### Multidimensional Arrays

In [11]:
import numpy as np

w1, w2, w3 = [0.3, 0.2, 0.5]

climate_data = np.array([
    [73, 57, 43], 
    [91, 88, 64], 
    [87, 134, 58], 
    [69, 96, 70]
])

weights = np.array([w1, w2, w3])

In [12]:
climate_data

array([[ 73,  57,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [ 69,  96,  70]])

In [13]:
# shapre function gives the shape of the matrix

climate_data.shape # This gives answer is 4, 3 because there are 4 rows, and every row has 3 colums in it

(4, 3)

In [14]:
arr1 = np.array([
    [[21, 22], [23, 24], [25, 26]], 
    [[14, 15], [12, 11], [21, 32]]
])

arr1.shape # This gives answer as 2, 3, 2 because there are 2 rows having 3 columns having 2 colums inside each

(2, 3, 2)

In [15]:
arr1.dtype

# If an array contains even single floating point number, then the entire array is converted into a floating type

dtype('int32')

In [18]:
# Matrix Multiplication 

np.matmul(climate_data, weights)

# We can also do the same thing using 
climate_data @ weights

array([54.8, 76.9, 81.9, 74.9])

### Problem 

In [2]:
# Helps to import datasets
import urllib.request
import numpy as np

# Importing dataset
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [5]:
climate_data
climate_data.shape

(10000, 3)

In [7]:
weights = np.array([0.3, 0.2, 0.5])

yeilds = climate_data @ weights

yeilds

yeilds.shape

(10000,)

In [9]:
# Now we add the yeilds column to the climate data section
# Axis 0 means concatenating the data ias a new row
# Axis 1 means concatenating the data as a new column


# What does .reshape function do?
# It reshapes the array in a given order. Here we reshape the array having 10000 rows and 1 column

climate_result = np.concatenate((climate_data, yeilds.reshape(10000, 1)), axis=1)

climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [17]:
# Write the changes to a file 
np.savetxt('climate_result.txt', 
           climate_result, 
           fmt="%.2f",
           header="temperature, rainfall, humidity, yeild_apples",
           comments=''
        )

# What does the comments section do?
# This adds a particular symbol to the txt file, usually # so while reading it, it starts with comments


### Arithmetic Operations with numpy

In [21]:
import numpy as np

arr2 = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

arr3 = np.array([
    [1, 1, 1, 1], 
    [2, 3, 4, 5],  
    [2, 2, 2, 2]
])

result = arr2 + arr3

# Every element will be added with 10
result + 10

# Elementwise subtraction
result - arr2

# Similarly you can do all arithmetic operations
result.shape

(3, 4)

### Creating arrays

In [42]:
# All zeros
arr_zero = np.zeros((3, 2))

# All ones
arr_one = np.ones([2, 2, 3])
arr_one

# Identity Matrix
arr_iden = np.eye(3)

# Random Vector
np.random.rand(5)

# Random matrix
np.random.randn(2, 3)

# What is the difference between randn and rand
# randn generates random numbers with mean = 0 and variance = 1, it is majorly used in statistical purposes 
# rand generated random numbers from 0 to 1, it is used for general purposes to declare random weights

# Range with start, end and step 
np.arange(10, 90, 3)

# Equally spaced out numbers, here we say we want to start with 3 and end with 27 and want to have 9 elements equallt spaced
np.linspace(3, 27, 9)


array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])